### ISSUE TITLE
[Bug]: Construction stick gains free battery upgrade when inventory charging is enabled

### ISSUE THREAD

**Issue by alekthefirst** [Mrbysco/ConstructionSticks#1]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge/Neoforge version

21.1.84

### Minecraft version

1.21.1

### Mod version

1.0.0

### Java version

21.0.3

### Issue Description

Playing atm10 v 2.1 When autocrafting a construction stick via an ME system, the stick does not report having a battery upgrade while still in the ME system, then gains a free battery upgrade when moved to the inventory. Inventory charging via powah player transmitter is enabled, automatically charging the stick.

### Additional Information

Video on how to reproduce: https://i.imgur.com/NkIB9f5.mp4

No relevant errors to be found in either latest.log or debug.log

**Comment by alekthefirst** [comment]
Update: The me system is not relevant to the issue, just the inventory charging alone is enough to gain the free battery upgrade

**Comment by Mrbysco** [comment]
TODO: Change the energy capability to actually check if the upgrade is applied
