### ISSUE TITLE
[Bug]: Extra item for smithing recipe doesnt show as a recipe when using JEI+EMI. Had to look for item in source code.

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [Mrbysco/ConstructionSticks#5]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I am using the latest version of the mod

### Forge/Neoforge version

21.1.90

### Minecraft version

1.21.1

### Mod version

1.0.3

### Java version

21.0.3

### Issue Description

Extra item for smithing recipe doesnt show as a recipe when using JEI+EMI. Had to look for item in source code.

**Comment by Mrbysco** [comment]
Not much I can do about that without adding explicit EMI support which at this time is not planned
